- name: generate ddclient config file
  template: src=ddclient.conf.j2 dest={{ ddclient_config }} mode=0640 owner=root group={{ ddclient_group }}
  register: res
  notify: service ddclient restart

- name: manage service
  service: name={{ ddclient_service_name }} state=started enabled=yes
  when: not res.changed  
